title:
  german: Mit Zehnern multiplizieren
  english: Multiplying by tens
description: The student sees a multiplication exercise where both numbers are multiples
  of 10. The student have to finde the solution of the multiplication.
example: 'Exercise: 60*70 Correct Answer: 4200'
topic_id: 17
template: 01_simple_question_answer
text:
  text_question:
    german: 'Multipliziere.'
    english: 'Multiply.'
pyscript:
  imports: |
    import random
    from pyscript import document
    from pyweb import pydom
    from js import document
  globals: |
    answer = 0
    n1 = 0
    n2 = 0
  checker: |
    def check_answer(event):
      # Access the math-field element
      math_field = document.getElementById("equation")
      user_answer = math_field.getPromptValue('answer')
    
      if user_answer.isnumeric():
          user_answer = int(user_answer)
          is_correct = True if user_answer == answer else False
      else:
          is_correct = False

      return [is_correct, answer, user_answer]
  generator: |
    def generate(parent):
      global answer, n1, n2

      n1 = random.randint(1, 9) * 10
      n2 = random.randint(1, 9) * 10

      answer = n1 * n2
      equation = str(n1) + "\\cdot" +str(n2) +" = \\placeholder[answer]{}"

      question_element, answer_element = generate_template(parent)
      question_element.innerText="{{ text.text_question }}"
      answer_field = document.createElement("math-field")
      answer_field.id = "equation"
      answer_field.className = 'w-48'
      answer_field.setValue(equation)
      answer_field.mathVirtualKeyboardPolicy = "manual"
      answer_field.readonly = True
      answer_element.append(answer_field)

  details: |
    def get_details():
      return f"The current exercise is {n1}*{n2}. Therefore the correct answer is {answer}"
